language: java
sudo: false
include:
  - os: linux
    jdk: oraclejdk7
  - os: linux
    jdk: oraclejdk8
  - os: osx
    osx_image: xcode8
env:
  matrix:
    - NODE_VERSION=7 CC=clang CXX=clang++
    - NODE_VERSION=6 CC=clang CXX=clang++
    - NODE_VERSION=4 CC=clang CXX=clang++
before_install:
  - nvm install $NODE_VERSION
  - npm install
script:
  - npm test
notifications:
  email:
    on_success: "never"
